### ISSUE TITLE
Template Caching

### ISSUE THREAD

**Issue by zombor** [zombor/KOstache#2]
Caching might be desirable. See http://github.com/bobthecow/mustache.php/issues/#issue/2

**Comment by banks** [comment]
Esspecially support for caching partials in tempaltes. The mustach(5) docs state that where a section key is a lambda (or class method in PHP) the whole text to be parsed is sent effectively allowing caching of chunks of templates while the rest remain dynamic.

Not sure if this is currently possible with mustache.php

**Comment by leeoniya** [comment]
i rolled my own mustache flavor (in JS) from scratch because i felt some things like pragmas, implicit block context diving without explicit booleans and in-template delimiter switching were a bit much or unclear. my code includes partials caching, in fact there's no such thing as "partials" it's ALL just node cache.

the code is written significantly differently and much more flexible than the current JS implementation. there are slight syntax additions for much more flexibility and differences from the regular mustache, i think for the better clarity-wise. check it out, feel free to port: http://github.com/leeoniya/handlebar.js

sorry dont have docs yet, but have full unit tests there.

if you want to know more details let me know. if you're gonna port though, keep in mind i decided to change the bool structure a bit from what's currently committed to make it more flexible (looks exactly like the one you use):

truthy checks:

<pre>{{?active}}blah{{/active}} becomes {{active?}}blah{{/active}}</pre>

falsy checks:

<pre>{{!active}}blah{{/active}} becomes {{active!}}blah{{/active}}</pre>


it seems less logical at first, but when you consider the shorthands and other features that are implemented on top, it makes it more uniform. see issue http://github.com/leeoniya/handlebar.js/issues#issue/6

cheers!
Leon

**Comment by banks** [comment]
Leon: interesting work but not sure changing mustache syntax is such a brilliant idea - one of the selling points is that it is meant to be implementation/language agnostic so it is better to work with it than change it.

I guess caching of any section or partial is pretty easy in mustache.php because you can override the `_render` methods to just return a string from cache for given tag name. This ensures that you don't incur the overhead of cloning the view and parsing the rendered partial output (which presumably has no tags in any more!).

So actually I'm not even sure it is really worth trying to implement anything that clever at the module level - it is so easy for the developer to do what he wants already.

I guess one simple thing that might be nice would be to be able to set a lifetime on a view and then have it automatically retrieve form Kohana::cache() when render() is called or something.

**Comment by banks** [comment]
P.s. the mustache links at the bottom of the README don't work...

**Comment by zombor** [comment]
> I guess one simple thing that might be nice would be to be able to set a lifetime on a view and then have it automatically retrieve form Kohana::cache() when render() is called or something.

That's what I was thinking of.

**Comment by zeelot** [comment]
Here is a clever way to cache parts of a template:

Origin in ruby = http://ozmm.org/posts/higher_order_mustache.html

```
{{# cache_by_user_id}}
  Some expensive stuff.
{{/ cache_by_user_id}}

function cache_by_user_id()
{
    $view = $this;
    return function($string) use($view)
    {
        $cached_mustache = Cache::instance()->get('cached_mustache.'.$this->user->id, array());
        $cache = Arr::get($cached_mustache, $view);
        if ( ! $cache)
        {
            $cache = $view->render($string);
            $cached_mustache[$view] = $cache;
        }

        return $cache;
    };
}
```

You can expand on this example to make more complex cache systems, basically removing the need to render large portions of your 'static' mustache blocks.

**Comment by zombor** [comment]
I think caching belongs in the specific view models, not built into the template framework.
