### ISSUE TITLE
Implementing MustacheLoader for auto-loading partials

### ISSUE THREAD

**Issue by rafi** [zombor/KOstache#39]
Any ideas on how to implement [MustacheLoader](https://github.com/bobthecow/mustache.php/blob/master/MustacheLoader.php) with View classes to auto-load partials ?

**Comment by zombor** [comment]
I'm not sure it's needed? They are autoloaded already from the CFS with `find_file()`.

**Comment by rafi** [comment]
Partials are not auto-loaded, you need to set them every time in `Kostache::$_partials`

**Comment by zombor** [comment]
Right, that's what I meant.

**Comment by shadowhand** [comment]
Like @zombor said, it really isn't necessary to use MustacheLoader because any partial set in `$_partials` will be automatically loaded. But it seems to me the point of MustacheLoader is to automatically load partials without defining them. This might put you on the right track (put in your View's `__construct` method):

``` php
parent::__construct();
$this->_partials = new MustacheLoader(APPPATH.'templates/partials');
```

This makes a couple of negative assumptions in my opinion:
1. Only the application template directory is used, so no CFS support. Extend `MustacheLoader::pathName()` to get around this.
2. Your replacing something that is very explicit with magic. Magic has a tendency to confuse people, at best, or worse, fail miserably.

**Comment by rafi** [comment]
Thanks @shadowhand that's exactly what I meant: automatically load partials without defining them.
I agree with your 2 negative points. Thanks.
